### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by mcshane** [lh3/bgt#1]
I guess I'm a little too quick off the mark, but is something missing from the Makefile?

```make: *** No rule to make target `bgtview.o', needed by `bgt'. Stop.```

Also, extracting `k8` as in the instructions overwrites the `bgt` README.md with the `k8` README.md

**Comment by lh3** [comment]
Thanks. I forgot to "git add bgtview.c". Now added. I have also updated README.md to extract "k8-linux" only.

**Comment by mcshane** [comment]
Thanks.
