### ISSUE TITLE
Import VCF into existing bgt file

### ISSUE THREAD

**Issue by sndrtj** [lh3/bgt#11]
Is there any way to import a VCF containing additional samples into an existing bgt file? 

I've tried `bgt import -S prefix.bgt 1.vcf` followed by `bgt import -S prefix.bgt 2.vcf`, but this only seems to overwrite the existing file.

**Comment by lh3** [comment]
Sorry. It is not possible to achieve that with bgt. You have to merge VCF files first (e.g. with GATK or bcftools) and then import the merged file.
