### ISSUE TITLE
[W::vcf_parse1] can't find '10' in the sequence dictionary

### ISSUE THREAD

**Issue by SmDonkey** [lh3/bgt#13]
HI!
  when i try to run compress order:
  ./bgt import -S -o archive input.vcf
  Error occured

**Comment by lh3** [comment]
Probably because your VCF doesn't have ##contig lines.

**Comment by SmDonkey** [comment]
> Probably because your VCF doesn't have ##contig lines.

It is from 1000 gp, download address is http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/
In addition to，And I found some other VCF files that it couldn't compress

**Comment by lh3** [comment]
As I said, there no ##contig lines. You need to provide sequence names and lengths with -t.
