### ISSUE TITLE
getting private variants from an individual

### ISSUE THREAD

**Issue by pontikos** [lh3/bgt#9]
I'm trying to get variants seen in only one sample X in the cohort.

I'm trying:

```
bgt view -s,X -f 'AC1>0&&AC<=2' -G cohort.bgt
```

It's not working.  How can I achieve this?

**Comment by lh3** [comment]
It does not work because you are querying overlapping samples. Here is a not-so-clean workaroud: you add the sample name as a new field. For example:
```sh
cp cohort.bgt.spl cohort.bgt.spl.bak
awk -v FS="\t" -v OFS="\t" '{print $0,"name:Z:"$1}' cohort.bgt.spl.bak > cohort.bgt.spl
bgt view -s,X -s 'name!="X"' -f 'AC1>0&&AC2==0' -G cohort.bgt
```
Your new `cohort.bgt.spl` will look like:
```
sample1  ...  name:Z:sample1
sample2  ...  name:Z:sample2
```
Then you can use `-s 'name!="sample1"'` etc to select samples.
